language: haskell
script:
  - 'cabal configure --enable-tests && cabal build'
before_install:
  - 'sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ raring main universe"'
  - 'sudo apt-get update'
  - 'sudo apt-get install librados-dev'
